### PR TITLE
Fix #740 for FsStateStore.createAlias and removing usage of FileUtil.copy

### LINKED ISSUE #740: Fix Usage of FileUtil.copy() and FsStateStore.createAlias() function
`FsStateStore.createAlias` can leave a partial `current.jst` file if the function is interrupted during the execution of `FileUtil.copy`. Looking at the code in `FileUtil.copy` the code doesn't handle what happens if the copy is interrupted:

```
try {
  in = srcFS.open(src);
  out = dstFS.create(dst, overwrite);
  IOUtils.copyBytes(in, out, conf, true);
} catch (IOException e) {
  IOUtils.closeStream(out);
  IOUtils.closeStream(in);
  throw e;
}
```

Here are all the places `FileUtil.copy()` is being used:

```
./gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java: if (!FileUtil.copy(fs, src, fs, dst, false, fs.getConf())) {
./gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java: if (!FileUtil.copy(srcFs, src, dstFs, dst, true, false, dstFs.getConf())) {
./gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java: FileUtil.copy(this.fs, originalTablePath, this.fs, aliasTablePath, false, true, this.conf);
./gobblin-compaction/src/main/java/gobblin/compaction/hive/HdfsWriter.java: FileUtil.copy(fs, path, fs, new Path(destination), false, true, getConfiguration());
```

### PR DESCRIPTION
**Pull request by sahilTakiar**
* Fix for #740 
* Adds a overloaded `copyPath` method that allows writing data first to a temp file, and then committing the data using `renamePath`
    * This should fix the problems with `FsStateStore.createAlias`
* Removed all direct usages of `FileUtil.copy` with `HadoopUtils.copyPath`
* Unit tests are coming

@zliu41 can you review?

### CODE REVIEW

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 1]
```diff
@@ -132,29 +149,113 @@ public static void renamePath(FileSystem fs, Path oldName, Path newName) throws
...
+
+    if (!srcFs.exists(src)) {
+      throw new IOException(String.format("Cannot copy from %s to %s because src does not exist", src, dst));
+    }
+    try {
+      if (!FileUtil.copy(srcFs, src, dstFs, dst, deleteSource, overwriteDst, conf)) {
+        throw new IOException(String.format("Failed to copy %s to %s", src, dst));
+      }
+    } catch (IOException e1) {
+      FileSystem deleteFs;
```
Comment (zliu41) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: `FileUtil.copy` will throw `IOException` if `overwriteDst=false` and `dst` already exists. In this case you shouldn't attempt to delete `dst`

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 2]
```diff
@@ -132,29 +149,113 @@ public static void renamePath(FileSystem fs, Path oldName, Path newName) throws
...
+        throw new IOException(String.format("Cannot copy %s to %s because the dst exists", src, dst));
+      }
+      copyPath(srcFs, src, dstFs, tmp, false, overwriteTmp, conf);
+      try {
+        if (overwriteDst && dstFs.exists(dst)) {
+          deletePath(dstFs, dst, true);
+        }
+        renamePath(dstFs, tmp, dst);
+      } finally {
+        deletePath(dstFs, tmp, false);
```
Comment (zliu41) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: why should `recursive=false` here? If `src` is a directory it will throw IOException

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 3]
```diff
@@ -132,29 +149,113 @@ public static void renamePath(FileSystem fs, Path oldName, Path newName) throws
...
+      }
+      if (deleteSource) {
+        srcFs.delete(src, false);
```
Comment (zliu41) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: same question here

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 4]
```diff
@@ -132,29 +149,113 @@ public static void renamePath(FileSystem fs, Path oldName, Path newName) throws
...
   }
 
   /**
-   * A wrapper around {@link HadoopUtils#renamePath(FileSystem, Path, Path)} and
-   * {@link FileUtil#copy(FileSystem, Path, FileSystem, Path, boolean, Configuration)} which will rename the path
-   * if the src and dst filesystems are the same; otherwise, the src file will be moved the the dst filesystem.
-   * An {@link IOException} if {@link FileUtil#copy(FileSystem, Path, FileSystem, Path, boolean, Configuration)} returns false.
+   * Copies a src {@link Path} from a srcFs {@link FileSystem} to a dst {@link Path} on a dstFs {@link FileSystem}. If
+   * either the srcFs or dstFs are S3 {@link FileSystem}s (as dictated by {@link #S3_SCHEMES}) then data is directly
+   * copied from the src to the dst. Otherwise data is first copied to a tmp {@link Path}, which is then renamed to the
```
Comment (zliu41) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: It's better to explain here why S3 doesn't need tmp files.

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 5]
```diff
@@ -52,6 +54,21 @@
...
   public static final String HDFS_ILLEGAL_TOKEN_REGEX = "[\\s:\\\\]";
 
+  /**
+   * A {@link Collection} of all S3 schemes.
+   *
+   * <p>
+   *   The following important properties are useful to remember when writing code that is compatible with S3:
+   *   <ul>
+   *     <li>Renames are not atomic, and require copying the entire source file to the destination file</li>
+   *     <li>Writes to S3 will first go to the local filesystem, when the stream is closed the local file will be
```
Comment (kadaan) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: This is technically not true if you use s3a and call moveFromLocalFile.  In that case, the file is not written to a temp file locally and then copied up.

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 6]
```diff
@@ -132,29 +149,113 @@ public static void renamePath(FileSystem fs, Path oldName, Path newName) throws
...
+   * dst.
+   *
+   * @param srcFs the source {@link FileSystem} where the src {@link Path} exists
+   * @param src the {@link Path} to copy from the source {@link FileSystem}
+   * @param dstFs the destination {@link FileSystem} where the dst {@link Path} should be created
+   * @param dst the {@link Path} to copy data to
+   * @param tmp the temporary {@link Path} to use when copying data
+   * @param deleteSource true if the source should be deleted after the copy is complete, false otherwise
+   * @param overwriteDst true if the destination should be overwritten, false otherwise
+   * @param overwriteTmp true if the temp file should be overwritten, false otherwise
```
Comment (kadaan) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: Why would you ever choose overwriteTmp=true, but overwriteDst=false?

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 7]
```diff
@@ -132,29 +149,113 @@ public static void renamePath(FileSystem fs, Path oldName, Path newName) throws
...
+   * either the srcFs or dstFs are S3 {@link FileSystem}s (as dictated by {@link #S3_SCHEMES}) then data is directly
+   * copied from the src to the dst. Otherwise data is first copied to a tmp {@link Path}, which is then renamed to the
+   * dst.
+   *
+   * @param srcFs the source {@link FileSystem} where the src {@link Path} exists
+   * @param src the {@link Path} to copy from the source {@link FileSystem}
+   * @param dstFs the destination {@link FileSystem} where the dst {@link Path} should be created
+   * @param dst the {@link Path} to copy data to
+   * @param tmp the temporary {@link Path} to use when copying data
+   * @param deleteSource true if the source should be deleted after the copy is complete, false otherwise
```
Comment (kadaan) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: I know that hadoop does it this way, but I find it a little disgusting that copyPath has a bool that changes it to movePath.  To reduce duplication, I would prefer a common private method and clean versions of movePath and copyPath without the cruft of the deleteSource parameter.

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 8]
```diff
@@ -52,6 +54,21 @@
...
+   * <p>
+   *   The following important properties are useful to remember when writing code that is compatible with S3:
+   *   <ul>
+   *     <li>Renames are not atomic, and require copying the entire source file to the destination file</li>
+   *     <li>Writes to S3 will first go to the local filesystem, when the stream is closed the local file will be
+   *     uploaded to S3</li>
+   *   </ul>
+   * </p>
+   */
+  public static final Collection<String> S3_SCHEMES = ImmutableSortedSet.orderedBy(
```
Comment (kadaan) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: One issue here is that I think what we are really trying to identify are schemes which support atomic move/copy.  

This reminds me of a conversation with @ibuenros:
-- ibuenros
...
Maybe we could have a FileSystem decorator instead with a few of the methods you mention. We could then detect certain known schemes with incompatibilities and apply fixes across the entire code, but any FileSystem we haven't considered yet would still work appropriately.
  
-- kadaan
That would be great, but I think users of gobblin should be able to provide new decorators without having to extend gobblin itself.

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 9]
```diff
@@ -132,29 +149,113 @@ public static void renamePath(FileSystem fs, Path oldName, Path newName) throws
...
+   * Copies a src {@link Path} from a srcFs {@link FileSystem} to a dst {@link Path} on a dstFs {@link FileSystem}. If
+   * either the srcFs or dstFs are S3 {@link FileSystem}s (as dictated by {@link #S3_SCHEMES}) then data is directly
+   * copied from the src to the dst. Otherwise data is first copied to a tmp {@link Path}, which is then renamed to the
+   * dst.
+   *
+   * @param srcFs the source {@link FileSystem} where the src {@link Path} exists
+   * @param src the {@link Path} to copy from the source {@link FileSystem}
+   * @param dstFs the destination {@link FileSystem} where the dst {@link Path} should be created
+   * @param dst the {@link Path} to copy data to
+   * @param tmp the temporary {@link Path} to use when copying data
```
Comment (kadaan) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: It would be really nice if the caller didn't need to pass in a temp path.  For instance, if I'm developing and only work against s3, then the temp path is not something I ever need.  The opposite is true for you guys because you use HDFS.  Could we allow temp paths by filesystem to be specified in the global configuration?

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 10]
```diff
@@ -132,29 +149,113 @@ public static void renamePath(FileSystem fs, Path oldName, Path newName) throws
...
+   * </p>
+   *
+   * @param srcFs the source {@link FileSystem} where the src {@link Path} exists
+   * @param src the {@link Path} to copy from the source {@link FileSystem}
+   * @param dstFs the destination {@link FileSystem} where the dst {@link Path} should be created
+   * @param dst the {@link Path} to copy data to
+   * @param deleteSource true if the source should be deleted after the copy is complete, false otherwise
+   * @param overwriteDst true if the destination should be overwritten, false otherwise
+   */
+  public static void copyPath(FileSystem srcFs, Path src, FileSystem dstFs, Path dst, boolean deleteSource,
```
Comment (kadaan) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: As stated above, I really think that this should be transparent for users/developers. We should default to the safest, but possibly less performant, methods of performing actions.  In the case of filesystems, we should be able to decorate specific filesystems with more performant versions.  For instance, the base copy method could be the local->temp->dest version.  But, the s3* filesystems could be decorated to perform local->dest.

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java (hunk 1 above)
Comment (sahilTakiar) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: Good point.

I am going to replace `FileUtil.copy` completely because the method does not differentiate between errors occurring during copying of data vs. illegal arguments (both throw `IOException`)

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java (hunk 7 above)
Comment (sahilTakiar) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: Agreed, will make the changes.

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java (hunk 8 above)
Comment (sahilTakiar) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: I agree this is the approach we probably want to go with. I will create a follow up issue for this, but its going to require a little more effort, so lets do it in a different PR. I think the work in this PR will help do some of the initial work for this also.

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java (hunk 9 above)
Comment (sahilTakiar) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: Yes, it seems that the HDFS FileSystem originally tried to do something similar and had to make it configurable: https://issues.apache.org/jira/browse/HADOOP-11281

A `hdfs dfs -cp [src] [dst]` also uses a tmp file. It first copies data to `[dst]._COPYING_` and then does a rename. Seems there is also an option to disable this so that data is directly copied from the `src` to the `dst` (useful for S3). Unfortunately, the code doesn't seem to be publicly available.

**Comment by sahilTakiar** [comment]
I deleted the `copyPath` using tmp file method because its going to more effort than I originally anticipated, I still thinks it may be useful in the future, but is not strictly necessary for fixing #740

**Comment by sahilTakiar** [comment]
Updated. @zliu41 can you take another look?

**Comment by zliu41** [comment]
Please replace `FS_SCHEMES_NO_TMP_FILE_FOR_PUT` in `FsStateStore` with the one defined in `HadoopUtils`

File: gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java [hunk 11]
```diff
@@ -281,7 +280,7 @@ public void createAlias(String storeName, String original, String alias) throws
     Path aliasTablePath = new Path(new Path(this.storeRootDir, storeName), alias);
     // Make a copy of the original table as a work-around because
     // Hadoop version 1.2.1 has no support for symlink yet.
-    FileUtil.copy(this.fs, originalTablePath, this.fs, aliasTablePath, false, true, this.conf);
+    HadoopUtils.copyPath(this.fs, originalTablePath, this.fs, aliasTablePath, this.conf);
```
Comment (zliu41) [inline gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java]: Since `HadoopUtils.copyPath` can no longer overwrite, you need to first delete `current.jst`. However, if `current.jst` is deleted and then `copyPath` failed, there will be no `current.jst` and the next run will have no state.

Comment (kadaan) [inline gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java]: I concur.  Both copypath and movepath should have an overwrite option. It would also take care of the groundwork for #718.

Comment (sahilTakiar) [inline gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java]: I agree that these methods should have an `overwrite` flag, but adding it is a more work than I though it would be. I think we would have to replace `FileUtil.copy`. The problem is that `FileUtil.copy` has a few pre-condition checks that it does and if any fail it throws an `IOException`. It also throws on `IOException` if there is a problem copying the actual data. The problem is that there is no way to differentiate the two scenarios.

One of the requirements of `HadoopUtils.copyPath` should be that it doesn't leave partial data - it doesn't copy part of a file, fail and then quit. This can cause `EOFException`s (which is the original motivation for this PR), which is why in the `catch` block the the `dst` is deleted. This is harder when `overwrite=true` as the method should not delete the `dst` if a pre-condition fails.

Comment (sahilTakiar) [inline gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java]: For `FsStateStore` I changed it to write to a tmp path and then do a rename operation.

**Comment by sahilTakiar** [comment]
@zliu41 updated

File: gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java [hunk 12]
```diff
@@ -279,9 +276,13 @@ public void createAlias(String storeName, String original, String alias) throws
     }
 
     Path aliasTablePath = new Path(new Path(this.storeRootDir, storeName), alias);
+    Path tmpAliasTablePath = new Path(aliasTablePath.getParent(), new Path(TMP_FILE_PREFIX, aliasTablePath.getName()));
     // Make a copy of the original table as a work-around because
     // Hadoop version 1.2.1 has no support for symlink yet.
-    FileUtil.copy(this.fs, originalTablePath, this.fs, aliasTablePath, false, true, this.conf);
+    HadoopUtils.deleteIfExists(this.fs, tmpAliasTablePath, true);
+    HadoopUtils.copyPath(this.fs, originalTablePath, this.fs, tmpAliasTablePath, this.conf);
+    HadoopUtils.deleteIfExists(this.fs, aliasTablePath, true);
```
Comment (zliu41) [inline gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java]: If this line succeeds and the next line fails the state will be lost. One solution is to modify `FsDatasetStateStore.getLatestDatasetStatesByUrns` such that if `current.jst` doesn't exist, it will look for the most recent jst file.

Comment (sahilTakiar) [inline gobblin-metastore/src/main/java/gobblin/metastore/FsStateStore.java]: True. I would rather not have the `StateStore` default to the most recently created file as that violates the contract of the `get(storeName, tableName, stateId)` method which is suppose to either return the `State` associated with `tableName` or `null` if it does not exist.

Will try to think of a safer approach.

**Comment by sahilTakiar** [comment]
@zliu41 updated the `FsStateStore.createAlias` function

**Comment by sahilTakiar** [comment]
Actually, I'm not sure how this is going to solve the scenario where Azkaban executes a SLA kill on the job. Looking at `MRJobLauncher.cancelJob` only tries to kill the Hadoop job, but doesn't try to cancel anything else like the `Publisher` or `StateStore` serialization. So if `cancelJob` is invoked while the alias is created, the alias creation will probably continue to run until Azkaban just invokes a `kill -9` on the process. And we will just hit the same `EOFException`.

Any ideas? If we could use a RDMS instead I feel like DB transactions would make this a lot easier.

File: gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java [hunk 13]
```diff
@@ -132,29 +162,93 @@ public static void renamePath(FileSystem fs, Path oldName, Path newName) throws
...
+  public static void copyFile(FileSystem srcFs, Path src, FileSystem dstFs, Path dst, boolean overwrite,
+      Configuration conf) throws IOException {
+
+    Preconditions.checkArgument(srcFs.isFile(src),
+        String.format("Cannot copy from %s to %s because src is not a file", src, dst));
+    Preconditions.checkArgument(overwrite || !dstFs.exists(dst),
+        String.format("Cannot copy from %s to %s because dst exists", src, dst));
+
+    try (InputStream in = srcFs.open(src); OutputStream out = dstFs.create(dst, overwrite)) {
+      IOUtils.copyBytes(in, out, conf, false);
```
Comment (zliu41) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: This seems to have the same problems as before. If this line fails, `current.jst` will either be a partially copied file (if line 247 is not executed, e.g., SLA kill or OOM) or gone.

There doesn't seem to be an easy way to guarantee that if the new `current.jst` isn't successfully generated, the previous `current.jst` must be restored. So I still think modifying `FsDatasetStateStore.getLatestDatasetState` is a better approach. I don't think it violates any contract, because `current.jst` is just a convenient way to find the latest `jst` file (so that we don't need to list all `jst` files and sort them). If somehow `current.jst` failed to be generated, I don't see a problem of using the latest `jst` file.

Comment (sahilTakiar) [inline gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java]: The problem is that the javadoc of `StateStore` doesn't make any mention of using `current`. So if I want to implement a new `StateStore` called `MySqlStateStore`, I have to know that I also need to handle the scenario that if `current` is passed in as the `tableName` that the application is expecting the `MySqlStateStore` to return the latest `State`.

A user who just looks at the `StateStore` interface wouldn't know that. I think adding `StateStore.getLatest` would be a better way of doing this.

I'm not sure how much this matters considering `StateStore` is used in a very specific way, but lets just sync up tomorrow after the stand up.

**Comment by sahilTakiar** [comment]
@zliu41 updated, the only real change is that `copyPath` now catches `Throwable` instead of `Exception`, and I added a shutdown hook in `AbstractJobLauncher` to interrupt the main thread.

Adding a feature to `FsDatasetStateStore` to treat a `tableName` as `current` equivalent to the latest `.jst` files is slightly more difficult that originally thought, and the solution is a little hacky. The methods `getLatestDatasetState` and `getLatestDatasetStatesByUrns` would both have to be modified. The problem is that each dataset will have its own `-current.jst` file, I can explain more in person.

**Comment by zliu41** [comment]
If we keep `current.jst`, then if copy fails, the previous `current.jst` needs to be restored. This doesn't seem to be the case in the current approach.

**Comment by sahilTakiar** [comment]
@zliu41 `HadoopUtils.copyFile` has been updated

**Comment by zliu41** [comment]
LGTM
